services:
  db:
    image: mysql:8.0
    container_name: db_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_data_storytelling
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./Backend_CMS
      dockerfile: dockerfile.dev
    container_name: backend_dev
    volumes:
      - ./Backend_CMS:/var/www/symfony:delegated
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/cms_data_storytelling"
      APP_ENV: dev
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_dev
    ports:
      - "8080:80"
    volumes:
      - ./Backend_CMS:/var/www/symfony:delegated
      - ./Backend_CMS/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./Frontend_CMS
      dockerfile: dockerfile.dev
    container_name: frontend_dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://nginx/api"
    volumes:
      - ./Frontend_CMS:/app:cached
      - ./Frontend_CMS/node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - nginx

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_dev
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
  frontend_node_modules:
